---
apiVersion: v1
kind: Secret
metadata:
  name: "WORKER-NAME-bmc-secret"
  namespace: openshift-machine-api

type: Opaque
data:
  username: "IDRAC-USER"
  password: "IDRAC-PASSWORD"

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: "WORKER-NAME"
  namespace: openshift-machine-api
spec:
  online: true
  bmc:
    address: ipmi://IPMI_ADDRESS:623
    credentialsName: "WORKER-NAME-bmc-secret"
  hardwareProfile: unknown
  bootMACAddress: "PROVISIONING-MAC"
  bootMode: legacy
  userData:
    name: worker-user-data
    namespace: openshift-machine-api
